// environment.js
// NOTE: Environment props are now dynamically generated by the MapBuilder in maps.js!
// This file acts as a legacy adapter to prevent old require() statements from breaking.

const mapsAdapter = typeof window !== 'undefined' ? window : require('./maps');

const env = {
    // Dynamic passthrough for the active map's props
    getPropsForMap: function(mapName) {
        return mapsAdapter.getMapProps(mapName);
    }
};

if (typeof module !== 'undefined' && module.exports) module.exports = env;
else window.GameEnv = env;
